FROM node:24.15 AS builder
WORKDIR /app
COPY ../Package*.json ./
RUN npm install
COPY ../ ./
RUN npm run build

FROM nginx
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx","-g", "daemon off;"] #Should be written only once on docker